apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: skateshop
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      containers:
        - name: skateshop-frontend
          image: ciucurdaniel/skateshop-frontend:latest
          ports:
          - containerPort: 9000
          # readinessProbe:
          #   initialDelaySeconds: 5
          #   httpGet:
          #     path: "/health"
          #     port: 8080
          # livenessProbe:
          #   initialDelaySeconds: 5
          #   httpGet:
          #     path: "/health"
          #     port: 8080
          env:
          - name: PORT
            value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skateshop
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30007
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-external
#   namespace: skateshop
# spec:
#   type: LoadBalancer
#   selector:
#     app: frontend
#   ports:
#   - name: http
#     port: 80 # this one is the port of the service itself
#     targetPort: 8080 # this one is port of the pod